"""The planning context's events: a request for itineraries, and the proposal answering it."""

from datetime import date, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, Field

from agentic_eda.contracts import EventContract, event

from ..event_types import ITINERARY_PROPOSED, ITINERARY_REQUESTED


class Money(BaseModel):
    """An amount in one currency."""

    amount: float
    currency: str = Field(description="ISO 4217 code, such as USD.")


class Stop(BaseModel):
    """One place the trip stays, in travel order."""

    city: str
    arrive: date
    depart: date


@event(ITINERARY_REQUESTED, order_per="trip_id")
class ItineraryRequested(EventContract):
    """A request for a trip itinerary. Generated by someone, for example by another agent or system."""

    trip_id: int = Field(description="Identifies the trip across all of its events.")
    origin: str = Field(description="The city where the trip starts and ends.")
    stops: list[Stop] = Field(min_length=1, description="The places to stay, in travel order.")
    travellers: int = Field(ge=1)
    budget: Money | None = Field(
        description="Upper limit for the whole trip and all travellers. Null means no limit."
    )
    preferences: str = Field(description="Free text in the customer's own words.")
    car_class: str | None = Field(
        description="The class of rental car wanted. Null means no car is wanted."
    )


class Offer(BaseModel):
    """What a supplier quoted for an item, and until when the quote holds."""

    supplier: str
    offer_id: str = Field(description="The supplier's own identifier for the quote.")
    price: Money = Field(description="For all travellers together.")
    valid_until: datetime


class FlightItem(BaseModel):
    """One flight of an itinerary, its times in UTC."""

    kind: Literal["flight"]
    origin: str
    destination: str
    departs: datetime
    arrives: datetime
    fare_conditions: str = Field(
        description="The fare's rules in words, such as 'exchange for 150, no refund'."
    )
    offer: Offer | None = Field(description="Null when the item was planned without a quote.")


class StayItem(BaseModel):
    """One hotel stay of an itinerary."""

    kind: Literal["stay"]
    city: str
    hotel: str
    check_in: date
    check_out: date
    cancellation: str = Field(description="The rate plan's cancellation terms in words.")
    offer: Offer | None = Field(description="Null when the item was planned without a quote.")


class Itinerary(BaseModel):
    """One ranked way to make the trip, its items in travel order."""

    rank: int = Field(ge=1, description="Position in the proposal. 1 is the recommended one.")
    label: str = Field(description="What it optimises: cheapest, fastest, or best value.")
    rationale: str = Field(description="What this itinerary trades against the others.")
    items: list[Annotated[FlightItem | StayItem, Field(discriminator="kind")]] = Field(
        min_length=1
    )
    total: Money = Field(description="The price of all items, for all travellers together.")


@event(ITINERARY_PROPOSED, order_per="trip_id")
class ItineraryProposed(EventContract):
    """Planning's answer to one request: one to three ranked itineraries."""

    trip_id: int = Field(description="Identifies the trip across all of its events.")
    proposal_id: str = Field(description="Identifies the proposal. Generated by the Planner.")
    itineraries: list[Itinerary] = Field(min_length=1, max_length=3, description="Best first.")
