"""The planning context's events: a request for itineraries, and the proposal answering it."""

from datetime import date, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, Field, model_validator

from agentic_eda.contracts import EventContract, event

from ..event_types import ITINERARY_PROPOSED, ITINERARY_REQUESTED


class Money(BaseModel):
    """An amount in one currency."""

    amount: float
    currency: str = Field(description="ISO 4217 code, such as USD.")


class OriginDestination(BaseModel):
    """One journey the travellers want to make, with or without connections."""

    origin: str = Field(description="IATA city or airport code, such as NYC.")
    destination: str = Field(description="IATA city or airport code, such as MAD.")
    departure_date: date


class Stay(BaseModel):
    """One hotel stay the travellers want."""

    city: str = Field(description="IATA city code, such as MAD.")
    check_in: date
    check_out: date
    rooms: int = Field(ge=1)


class Child(BaseModel):
    """One traveller under 18."""

    age: int = Field(ge=0, le=17, description="In years at the end of the trip.")
    own_seat: bool = Field(description="False only for an infant under 2 held by an adult.")

    @model_validator(mode="after")
    def _only_an_infant_is_held(self):
        if not self.own_seat and self.age >= 2:
            raise ValueError("a traveller of 2 or older has a seat of their own")
        return self


@event(ITINERARY_REQUESTED, order_per="trip_id")
class ItineraryRequested(EventContract):
    """A request for a trip itinerary. Generated by someone, for example by another agent or system."""

    trip_id: int = Field(description="Identifies the trip across all of its events.")
    origin_destinations: list[OriginDestination] = Field(
        min_length=1, description="The journeys wanted, in travel order."
    )
    stays: list[Stay] = Field(description="The hotel stays wanted. Empty when none is wanted.")
    adults: int = Field(ge=1, description="Travellers of 18 or older.")
    children: list[Child] = Field(description="Every traveller under 18. Empty when there is none.")
    budget: Money | None = Field(
        description="Upper limit for the whole trip and all travellers. Null means no limit."
    )
    preferences: str = Field(description="Free text in the customer's own words.")
    car_class: str | None = Field(
        description="The class of rental car wanted. Null means no car is wanted."
    )

    @model_validator(mode="after")
    def _every_held_infant_has_an_adult(self):
        held = sum(1 for child in self.children if not child.own_seat)
        if held > self.adults:
            raise ValueError("an adult holds one infant at most")
        return self


class Offer(BaseModel):
    """What a supplier quoted for an item, and until when the quote holds."""

    supplier: str
    offer_id: str = Field(description="The supplier's own identifier for the quote.")
    price: Money = Field(description="For all travellers together.")
    valid_until: datetime


class FlightSegment(BaseModel):
    """One flight under one flight number, its times in UTC."""

    carrier: str = Field(description="IATA airline code, such as WW.")
    number: str = Field(description="The flight number without the carrier, such as 421.")
    origin: str = Field(description="IATA airport code, such as JFK.")
    destination: str = Field(description="IATA airport code, such as MAD.")
    departs: datetime
    arrives: datetime


class FlightItem(BaseModel):
    """One journey of an itinerary, as the flights serving it."""

    kind: Literal["flight"]
    segments: list[FlightSegment] = Field(
        min_length=1, description="In travel order. More than one means a connection."
    )
    fare_conditions: str = Field(
        description="The fare's rules in words, such as 'exchange for 150, no refund'."
    )
    offer: Offer | None = Field(description="Null when the item was planned without a quote.")


class StayItem(BaseModel):
    """One hotel stay of an itinerary."""

    kind: Literal["stay"]
    city: str = Field(description="IATA city code, such as MAD.")
    hotel: str
    room: str = Field(description="The type of room, such as double.")
    check_in: date
    check_out: date
    rate_plan: str = Field(description="The supplier's name for the rate, such as FLEXIBLE.")
    cancellation: str = Field(description="The rate plan's cancellation terms in words.")
    offer: Offer | None = Field(description="Null when the item was planned without a quote.")
    backup: "StayItem | None" = Field(
        description="The stay to reserve when this one cannot be. Null means none."
    )


class Itinerary(BaseModel):
    """One ranked way to make the trip, its items in travel order."""

    rank: int = Field(ge=1, description="Position in the proposal. 1 is the recommended one.")
    label: str = Field(description="What it optimises: cheapest, fastest, or best value.")
    rationale: str = Field(description="What this itinerary trades against the others.")
    items: list[Annotated[FlightItem | StayItem, Field(discriminator="kind")]] = Field(
        min_length=1
    )
    total: Money = Field(description="The price of all items, for all travellers together.")


@event(ITINERARY_PROPOSED, order_per="trip_id")
class ItineraryProposed(EventContract):
    """Planning's answer to one request: one to three ranked itineraries."""

    trip_id: int = Field(description="Identifies the trip across all of its events.")
    proposal_id: str = Field(description="Identifies the proposal. Generated by the Planner.")
    itineraries: list[Itinerary] = Field(min_length=1, max_length=3, description="Best first.")
